# Change these first
owner: Fellow-Consulting-AG # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CloudIntegration Public
    url: https://cloudintegration.eu/
  - name: Extraction and Classifications API
    url: https://fellowkv2.cloudintegration.eu/
  - name: Doc Square App
    url: https://doc2app.cloudintegration.eu/
  - name: Doc Square Landing Page
    url: https://doc2landing.cloudintegration.eu/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cloudintegration.eu
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://n8n-io.github.io/n8n-cloud-status/themes/polydocs.css
  name: Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: App
      href: https://doc2app.cloudintegration.eu/
    - title: Polydocs
      href: https://polydocs.io
    - title: Docs
      href: https://docs.cloudintegration.io

# status-website:
#   baseUrl: /upptime # where "repo" is your repository name
#   name: Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
