# Change these first
owner: Fellow-Consulting-AG # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CloudIntegration Public
    url: https://cloudintegration.eu/
  - name: Extraction and Classifications API
    url: https://fellowkv2.cloudintegration.eu/
  - name: Doc &sup2; App
    url: https://doc2app.cloudintegration.eu/
  - name: Doc &sup2; Landing Page
    url: https://doc2landing.cloudintegration.eu/

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cloudintegration.eu
  # baseUrl: /your-repo-name
  logoUrl: https://polydocs.io/wp-content/uploads/2022/04/Icon.svg
  themeUrl: https://status.cloudintegration.eu/themes/polydocs.css
  name: Status
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "Disclaimer: the Instance Cluster monitor shows the general health of the CloudIntegration cluster."
  navbar:
    - title: App
      href: https://doc2app.cloudintegration.eu/
    - title: Polydocs
      href: https://polydocs.io
    - title: Docs
      href: https://doc.cloudintegration.io
i18n:
  footer: "[Polydocs](https://polydocs.io)"
  

# status-website:
#   baseUrl: /upptime # where "repo" is your repository name
#   name: Status

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
